# -*- coding: utf-8 -*-
"""Assignment 1 pattern .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vehqsDD3Oxkw4y-EueZBbrPkcFq4gpbK

program to find min(x-2)^2
"""

#function to calculate the gradient
def g(x):
  return 2*(x-1)

#intialize variable x
x=3
learning_rate=0.001

for i in range(5000):
  x=x-learning_rate*g(x)
print(x)